version: '2'

services:
  wildfly:
    ## https://github.com/wildfly/wildfly/blob/24.0.1.Final/pom.xml
    image: docker.io/bitnami/wildfly:24.0.1
    ports:
      - '8080:8080'
      - '9990:9990'
    volumes:
      - './wildfly_data:/bitnami'
    environment:
      - WILDFLY_PASSWORD=2zCcrBNJCL448ZH8Jvff7z
      - WILDFLY_MANAGEMENT_LISTEN_ADDRESS=172.18.0.2
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: GbWhZMVd5aX2ZT7ACjXTUg
      MYSQL_DATABASE: hoteladvisors
      MYSQL_USER: hoteladvisors
      MYSQL_PASSWORD: GbWhZMVd5aX2ZT7ACjXTUg
    volumes:
      - './mysql_data:/var/lib/mysql'

volumes:
  wildfly_data:
    driver: local